version: '3'
services:
  postgres:
    image: postgres:15
    hostname: "pg_server"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    network_mode: bridge
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-10-13T00-23-17Z
    volumes:
      - minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    network_mode: bridge
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: root12345
    command: server /data --console-address ":9001"
volumes:
  minio:
  data:
    driver: local
